export const properties: Record<string, string[]> = {
  "Care Product 1": [
    "Size: Small",
    "Color: Blue",
    "Material: Cotton",
    "Price: $20",
    "Brand: CareCo",
  ],
  "Care Product 2": [
    "Size: Medium",
    "Color: Red",
    "Material: Polyester",
    "Price: $25",
    "Brand: CareCo",
  ],
  "Care Product 3": [
    "Size: Large",
    "Color: Green",
    "Material: Silk",
    "Price: $30",
    "Brand: CareCo",
  ],
  "Care Product 4": [
    "Size: XL",
    "Color: Yellow",
    "Material: Linen",
    "Price: $22",
    "Brand: CareCo",
  ],
  "Care Product 5": [
    "Size: Small",
    "Color: White",
    "Material: Wool",
    "Price: $18",
    "Brand: CareCo",
  ],
  "Care Product 6": [
    "Size: Medium",
    "Color: Black",
    "Material: Polyester",
    "Price: $23",
    "Brand: CareCo",
  ],
  "Care Product 7": [
    "Size: Large",
    "Color: Pink",
    "Material: Cotton",
    "Price: $28",
    "Brand: CareCo",
  ],
  "Care Product 8": [
    "Size: XL",
    "Color: Purple",
    "Material: Linen",
    "Price: $26",
    "Brand: CareCo",
  ],
  "Care Product 9": [
    "Size: Medium",
    "Color: Brown",
    "Material: Silk",
    "Price: $32",
    "Brand: CareCo",
  ],
  "Care Product 10": [
    "Size: Small",
    "Color: Gray",
    "Material: Cotton",
    "Price: $24",
    "Brand: CareCo",
  ],

  "Baskale Product 1": [
    "Size: Small",
    "Color: Blue",
    "Material: Cotton",
    "Price: $30",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 2": [
    "Size: Medium",
    "Color: Red",
    "Material: Polyester",
    "Price: $35",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 3": [
    "Size: Large",
    "Color: Green",
    "Material: Silk",
    "Price: $40",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 4": [
    "Size: XL",
    "Color: Yellow",
    "Material: Linen",
    "Price: $32",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 5": [
    "Size: Small",
    "Color: White",
    "Material: Wool",
    "Price: $28",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 6": [
    "Size: Medium",
    "Color: Black",
    "Material: Polyester",
    "Price: $33",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 7": [
    "Size: Large",
    "Color: Pink",
    "Material: Cotton",
    "Price: $38",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 8": [
    "Size: XL",
    "Color: Purple",
    "Material: Linen",
    "Price: $36",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 9": [
    "Size: Medium",
    "Color: Brown",
    "Material: Silk",
    "Price: $42",
    "Brand: BaskaleCraft",
  ],
  "Baskale Product 10": [
    "Size: Small",
    "Color: Gray",
    "Material: Cotton",
    "Price: $34",
    "Brand: BaskaleCraft",
  ],

  "Morocral Product 1": [
    "Size: Small",
    "Color: Blue",
    "Material: Cotton",
    "Price: $25",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 2": [
    "Size: Medium",
    "Color: Red",
    "Material: Polyester",
    "Price: $30",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 3": [
    "Size: Large",
    "Color: Green",
    "Material: Silk",
    "Price: $35",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 4": [
    "Size: XL",
    "Color: Yellow",
    "Material: Linen",
    "Price: $28",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 5": [
    "Size: Small",
    "Color: White",
    "Material: Wool",
    "Price: $24",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 6": [
    "Size: Medium",
    "Color: Black",
    "Material: Polyester",
    "Price: $29",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 7": [
    "Size: Large",
    "Color: Pink",
    "Material: Cotton",
    "Price: $34",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 8": [
    "Size: XL",
    "Color: Purple",
    "Material: Linen",
    "Price: $32",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 9": [
    "Size: Medium",
    "Color: Brown",
    "Material: Silk",
    "Price: $38",
    "Brand: MorocralStyle",
  ],
  "Morocral Product 10": [
    "Size: Small",
    "Color: Gray",
    "Material: Cotton",
    "Price: $30",
    "Brand: MorocralStyle",
  ],
};
